# Generated by Django 4.1.7 on 2023-04-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_rename_user_assignmentsubmissions_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentsubmissions',
            name='answer',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='assignmets',
            name='question',
            field=models.CharField(max_length=1000),
        ),
    ]
