# Generated by Django 4.1.7 on 2023-04-01 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_staffs_department_alter_students_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('staff_permissions', 'Staff Permissions'), ('students_permissions', 'Students Permissions'))},
        ),
    ]
