# Generated by Django 4.1.7 on 2023-04-03 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_subject_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='register_number',
            field=models.CharField(default=0, max_length=25),
            preserve_default=False,
        ),
    ]
